### ISSUE TITLE
sections with text - text edit

### ISSUE THREAD

**Issue by carloslopesalves** [leihla/major#42]
Não é possível fazer line breaks nem listas nos conteúdos texto.

![image](https://user-images.githubusercontent.com/42380781/71409512-c77beb80-2639-11ea-95cd-c7e61bde1bbc.png)

![image](https://user-images.githubusercontent.com/42380781/71409533-d5317100-2639-11ea-8968-b4e310ddb095.png)

![image](https://user-images.githubusercontent.com/42380781/71409595-1b86d000-263a-11ea-8e44-be598e9895ab.png)

**Comment by danielfdsilva** [comment]
@carloslopesalves As `line breaks` são renderizadas como `<p>`. Aconselho a meteres margens. Se quiseres mesmo usar `<br/>` podes colocar html diretamente, mas não aconselho.
Aqueles itens são uma lista, apenas não estão estilizados como tal
![image](https://user-images.githubusercontent.com/1090606/71478457-b375ec80-27e7-11ea-8c2f-38dca8c98ed4.png)

**Comment by carloslopesalves** [comment]
Ok entendido!
